### ISSUE TITLE
Access control issues in JSONWarehouse class

### ISSUE THREAD

**Issue by maxsokolov** [nickoneill/Pantry#10]
It's currently impossible to use Storage via Cocoapods due to access control issues in the **JSONWarehouse** class. **JSONWarehouse** marked as public, but important methods are not:

```swift
public class JSONWarehouse {
    //...
    func get<T: StorableDefaultType>(valueKey: String) -> T? {
       //...
    }
}
```
So method **get** is internal here and it's visible only for module where it is defined. See the Default Access Levels in [docs](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/AccessControl.html). When we use Storage via Cocoapods it connects as an independent module. So internal methods are not visible outside of Storage's module. 

Please mark methods that have to be visible outside as public.
Thank a lot! Storage is great!

**Comment by nickoneill** [comment]
Thanks for the report @maxsokolov! I noticed this as well. If you grab the `:head` version rather than the 0.1 release, you'll see that this is already fixed. You also get timed expiration in the newest code :)

**Comment by nickoneill** [comment]
This should be good for you in 0.2, let me know if you have any other issues!

**Comment by maxsokolov** [comment]
@nickoneill thanks a lot!
