### ISSUE TITLE
JSONWarehouse methods visibility

### ISSUE THREAD

**Issue by JanC** [nickoneill/Pantry#12]
Hi,
this looks like a nice project and I thought I give it a try. I integrated via CocoaPods and I'm getting a compile error. The `get` is not visible

```swift
extension TMDBMovie: Storable {
    init(warehouse: JSONWarehouse) {
        // Value of type 'JSONWarehouse' has no member 'get'
        originalTitle = warehouse.get("originalTitle")
    }
    func toDictionary() -> [String: AnyObject] {
        return ["originalTitle" : originalTitle ?? ""]
    }
}
```

Shouldn't they be declared as `public` ?

cheers

**Comment by nickoneill** [comment]
Yep, sorry about that. I'll get this visibility changed ASAP (and you shouldn't have to create your own toDictionary)

**Comment by nickoneill** [comment]
Just sent 0.2.1 with visibility changes for the warehouse (probably should be a shelf/cupboard/closet now?), let me know if that works for you.

**Comment by JanC** [comment]
thanks, I'll give it a shot, cheers
