### ISSUE TITLE
Updating cached objects

### ISSUE THREAD

**Issue by damirstuhec** [nickoneill/Pantry#13]
I have a question about updating cached objects. Let's say I have an array of custom objects which are cached. Then, I make a network request which returns the same set of objects but with updated properties. What are your ideas for handling those cases?

An easy solution would be to just clear the cache and save the new data, but that's not always acceptable.

Off topic question: I see that you have the `removeCache` function defined on `JSONWarehouse` object but its scope is not public. I'm wondering what is the recommended way to clear the cache? A case for that would be the user logging out.

Thanks and keep up!

**Comment by nickoneill** [comment]
Currently the new cache overwrites the old one whenever it's stored, no optimizations about which properties are updated. I would much rather develop a faster / more compact format for storing objects so it's quicker to do that whole file write.

I'm open to discussion but my general feeling right now is that if this is a situation that rewriting the cache becomes an issue, your use case might be better served by a real DB.

As for `removeCache`, I think we should wrap it in a public expire function that could eventually deal with any other expiration related tasks. It keeps the public method names more consistent as well.
