### ISSUE TITLE
Example code references 'Warehouseable'

### ISSUE THREAD

**Issue by barfoon** [nickoneill/Pantry#30]
Example code in the docs for Classes references `Warehouseable` which doesn't appear to be in the code anymore?

```Swift
required init(warehouse: Warehouseable) {
        self.id = warehouse.get("id") ?? "default_id"
}
```

![image](https://cloud.githubusercontent.com/assets/1120510/12654347/7f081ca2-c5c1-11e5-99de-74a6e76b0adb.png)

https://github.com/nickoneill/Pantry/blame/master/README.md#L133

An update to this section would be great.

Cheers,

**Comment by barfoon** [comment]
Looks like this should be `init(warehouse: JSONWarehouse)` now?

![image](https://cloud.githubusercontent.com/assets/1120510/12654568/9fb1aecc-c5c2-11e5-9c3e-aaf207a1da24.png)

**Comment by nickoneill** [comment]
This may be related to changes we've done since the last release... have you tried using `:head`? New release coming very soon.

**Comment by barfoon** [comment]
Thanks @nickoneill 
I ran pod install with 
```
use_frameworks!
pod 'Pantry'
```
and the code brought down didn't have `Warehouseable`

**Comment by nickoneill** [comment]
Can you try `pod 'Pantry', :head` and `pod install` again?

**Comment by barfoon** [comment]
Yeah, that did it, thanks.

![image](https://cloud.githubusercontent.com/assets/1120510/12680565/8eacf760-c678-11e5-85ac-7b464b393f17.png)

![image](https://cloud.githubusercontent.com/assets/1120510/12680551/80ce7e48-c678-11e5-819d-10e9655acca4.png)

**Comment by nickoneill** [comment]
So it works for you now?

**Comment by barfoon** [comment]
@nickoneill Yes

**Comment by nickoneill** [comment]
Great! Will get that release out soon so others don't run into the same thing.

**Comment by barfoon** [comment]
Awesome! Cheers
