### ISSUE TITLE
Icon project template

### ISSUE THREAD

**Issue by souzainf3** [nickoneill/Pantry#36]
Which template you used to create the icon of this project ?

**Comment by nickoneill** [comment]
Hey @souzainf3, I don't remember if I used a template. It's pretty simple: stack some rounded rectangles and change the perspective on a while outline icon until it fits.

**Comment by JanC** [comment]
You should be able to add a icon on top of it. rotate and transform it

[Sketch source here](https://dl.dropboxusercontent.com/u/1326174/Pentry.sketch)

![pentry](https://cloud.githubusercontent.com/assets/707703/13060217/2b06e4e4-d430-11e5-8730-4a9039d74173.png)

**Comment by nickoneill** [comment]
Exactly @JanC :) thanks for the template!

**Comment by souzainf3** [comment]
Thank you guys!
