### ISSUE TITLE
Pantry crashes when trying to expire a non-existent key

### ISSUE THREAD

**Issue by DrewKiino** [nickoneill/Pantry#41]
try this... 
```
Pantry.expire("Test")
```
assuming the key "Test" does not exist, and the framework will crash

 I was looking at your code and I see that you did a force unwrapping within the delete cache function, I know try methods are cumbersome because this framework is based of speed of code but maybe do a safe unwrap under the layer and if the unwrapping is unsafe then just return nil perhaps?

![screen shot 2016-06-04 at 12 48 58 pm](https://cloud.githubusercontent.com/assets/13005359/15801713/c2793ee4-2a52-11e6-914e-6441ca252f18.png)

**Comment by nickoneill** [comment]
Hi @DrewKiino, this is fixed in master. I haven't made a new release in a while, it's probably close to that time again.

**Comment by DrewKiino** [comment]
okay, are you going to release the fix anytime soon? ;)

**Comment by nickoneill** [comment]
Not until July at the earliest. You can tell cocoapods or carthage to use the most up-to-date code with either `:head` or `master` though.

**Comment by nickoneill** [comment]
Resolved with new releases
