### ISSUE TITLE
Next release?

### ISSUE THREAD

**Issue by ceeK** [nickoneill/Pantry#47]
Quick question: as the most recent release was last December, can we expect a release anytime soon?

**Comment by nickoneill** [comment]
Yep, I'll take care of it this week.

**Comment by kafejo** [comment]
Really? 🙃

**Comment by nickoneill** [comment]
Wheeeeeee! I know this isn't going to be any easier the longer I wait...

**Comment by damianesteban** [comment]
Looking forward to using this in a new project.

**Comment by chasemccoy** [comment]
Can you push a release? I am trying to use this in a work project but I'm running into some issues that look as if they have been fixed since the last release.

**Comment by damianesteban** [comment]
Any timeline on Swift 3.0 compatibility?  I could try and help out later this week.

**Comment by jkyin** [comment]
Swift 3?

**Comment by nickoneill** [comment]
Swift 2 release is 0.2.2, swift 3 is released as 0.3. Thanks for waiting :)
