### ISSUE TITLE
Nested Dictionary Rejected by Pantry 

### ISSUE THREAD

**Issue by SikandAlex** [nickoneill/Pantry#48]
I have a multiple-nested dictionary of type:

`Dictionary<String, Dictionary<String, Dictionary<String, Int>>>`

and when I call `Pantry.pack` on it this is the error message I get this error message

`Cannot invoke 'pack' with an argument list of type (Dictionary<String, Dictionary<String, Dictionary<String, Int>>>, key: String)`

**Comment by nickoneill** [comment]
Hey @SikandAlex, I think you're being too specific for Pantry here. We need to specify `pack` for each specific type that we can pack/unpack and I don't think the type system will automatically downcast to the `Dictionary<String, AnyObject>` that we support.

Try one of two suggestions:
* Try it with the `Dictionary<String, AnyObject>` type and then optionally cast back to your expected type
* Replace your object with a struct and write your own `init` method (this will probably still be an issue if one of your properties is still of type `Dictionary<String, Dictionary<String, Dictionary<String, Int>>>`)
* Create a Pantry extension which specifies `pack` and `unpack` for your specific type? I haven't tried this yet but I suspect it could work.

**Comment by SikandAlex** [comment]
Ok I just tried it with `Dictionary<String, AnyObject>` but it gave me the same issue

`Cannot invoke pack with an argument list of type (Dictionary<String, AnyObject>, key: String)`

**Comment by SikandAlex** [comment]
I've tried making custom structs to get around having to have so many layers of nesting but Swift is not recognizing Warehousable as a type even after installing the pod?

**Comment by nickoneill** [comment]
@SikandAlex The `Warehousable` issue is a separate thing - use `master` via cocoapods rather than the versioned release for the fix right now.
